DROP DATABASE IF EXISTS data;

CREATE DATABASE data;

USE data;

DROP TABLE IF EXISTS client_0;
CREATE TABLE client_0
(
	ID INT,
	SHIPPING_MODE VARCHAR(100),
	SHIPPING_PRICE VARCHAR(100),
	WARRANTIES_FLG VARCHAR(100),
	WARRANTIES_PRICE VARCHAR(100),
	CARD_PAYMENT INT(1),
	COUPON_PAYMENT INT(1),
	RSP_PAYMENT INT(1),
	WALLET_PAYMENT INT(1),
	PRICECLUB_STATUS VARCHAR(100),
	REGISTRATION_DATE VARCHAR(100),
	PURCHASE_COUNT VARCHAR(100),
	BUYER_BIRTHDAY_DATE VARCHAR(100),
	BUYER_DEPARTMENT INT,
	BUYING_DATE VARCHAR(100),
	SELLER_SCORE_COUNT VARCHAR(100),
	SELLER_SCORE_AVERAGE INT,
	SELLER_COUNTRY VARCHAR(100),
	SELLER_DEPARTMENT VARCHAR(100),
	PRODUCT_TYPE VARCHAR(100),
	PRODUCT_FAMILY VARCHAR(100),
	ITEM_PRICE VARCHAR(100),
	COUNTRY_KEY VARCHAR(100)
);

LOAD DATA LOCAL INFILE 'C:/Users/Utilisateur/Desktop/dev/sql/tp_sql_1/Base_eval.csv' 
INTO TABLE data.client_0 
FIELDS TERMINATED BY ';'
IGNORE 1 LINES;

SELECT COUNT(*) FROM client_0;
SELECT * FROM client_0 LIMIT 100;


SELECT COUNT(*) FROM (SELECT
	ID,
	SHIPPING_MODE,
	SHIPPING_PRICE,
	WARRANTIES_FLG,
	WARRANTIES_PRICE,
	CARD_PAYMENT,
	COUPON_PAYMENT,
	RSP_PAYMENT,
	WALLET_PAYMENT,
	PRICECLUB_STATUS,
	REGISTRATION_DATE,
	PURCHASE_COUNT,
	BUYER_BIRTHDAY_DATE,
	BUYER_DEPARTMENT,
	BUYING_DATE,
	SELLER_SCORE_COUNT,
	SELLER_SCORE_AVERAGE,
	SELLER_COUNTRY,
	SELLER_DEPARTMENT,
	PRODUCT_TYPE,
	PRODUCT_FAMILY,
	ITEM_PRICE,
	COUNTRY_KEY,
	COUNT(*)
FROM
	client_0
GROUP BY 
	ID,
	SHIPPING_MODE,
	SHIPPING_PRICE,
	WARRANTIES_FLG,
	WARRANTIES_PRICE,
	CARD_PAYMENT,
	COUPON_PAYMENT,
	RSP_PAYMENT,
	WALLET_PAYMENT,
	PRICECLUB_STATUS,
	REGISTRATION_DATE,
	PURCHASE_COUNT,
	BUYER_BIRTHDAY_DATE,
	BUYER_DEPARTMENT,
	BUYING_DATE,
	SELLER_SCORE_COUNT,
	SELLER_SCORE_AVERAGE,
	SELLER_COUNTRY,
	SELLER_DEPARTMENT,
	PRODUCT_TYPE,
	PRODUCT_FAMILY,
	ITEM_PRICE,
	COUNTRY_KEY
HAVING COUNT(*) > 1) AS t1;

DROP TABLE IF EXISTS client_1;
CREATE TABLE client_1 AS
SELECT DISTINCT * FROM client_0

SELECT COUNT(*) FROM client_1
SELECT * FROM client_1 LIMIT 100;

SELECT COUNT(*)
FROM client_1
WHERE SELLER_DEPARTMENT = -1;

DROP TABLE IF EXISTS vendeur_1;
CREATE TABLE vendeur_1 AS
SELECT * 
FROM client_1 
WHERE SELLER_DEPARTMENT = -1;

SELECT COUNT(*) FROM vendeur_1;
SELECT * FROM vendeur_1 LIMIT 100;
SELECT SELLER_COUNTRY FROM vendeur_1 GROUP BY SELLER_COUNTRY;

DROP TABLE IF EXISTS vendeur_2;
CREATE TABLE vendeur_2 AS
SELECT * 
FROM client_1 
WHERE SELLER_DEPARTMENT <> -1;

SELECT COUNT(*) FROM vendeur_2;
SELECT * FROM vendeur_2 LIMIT 100;
SELECT SELLER_COUNTRY FROM vendeur_2 GROUP BY SELLER_COUNTRY;

SELECT 
	(SELECT COUNT(*)
	FROM vendeur_2
	WHERE 
		UPPER(BUYING_DATE) LIKE '%MAI%' AND 
		SELLER_SCORE_AVERAGE > (SELECT AVG(SELLER_SCORE_AVERAGE) FROM vendeur_2)
	)
	 / COUNT(*) FROM vendeur_2
	 WHERE 
		UPPER(BUYING_DATE) LIKE '%MAI%';

SELECT
	PRODUCT_FAMILY,
	SUM(CASE 
        WHEN INSTR(PURCHASE_COUNT, "<") <> 0 AND SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) = "" THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) / 2
        WHEN INSTR(PURCHASE_COUNT, "<") <> 0 THEN SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) + (SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) - SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1)) / 2
        WHEN INSTR(PURCHASE_COUNT, ">") <> 0 THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, ">") + 1) / 2
        ELSE 0
    END) AS PURCHASE_COUNT_AVG
FROM client_1
GROUP BY PRODUCT_FAMILY;

SELECT
	SUM(CASE 
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 AND SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) = "" THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) / 2
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 THEN SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) + (SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) - SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1)) / 2
		WHEN INSTR(PURCHASE_COUNT, ">") <> 0 THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, ">") + 1) / 2
		ELSE 0
	END) AS FOREIGNER,
	(SELECT SUM(CASE 
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 AND SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) = "" THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) / 2
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 THEN SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) + (SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) - SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1)) / 2
		WHEN INSTR(PURCHASE_COUNT, ">") <> 0 THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, ">") + 1) / 2
		ELSE 0
	END) FROM vendeur_2) AS FRENCH
FROM vendeur_1;

DROP TABLE IF EXISTS produit_1;
CREATE TABLE produit_1 AS
SELECT 
	PRODUCT_TYPE, 
	PRODUCT_FAMILY,
	SUM((CASE 
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 AND SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) = "" THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) / 2
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 THEN SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) + (SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) - SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1)) / 2
		WHEN INSTR(PURCHASE_COUNT, ">") <> 0 THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, ">") + 1) / 2
		ELSE 0
	END) * (CASE 
		WHEN INSTR(ITEM_PRICE, "<") <> 0 AND SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1) = "" THEN SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, "<") + 1) / 2
		WHEN INSTR(ITEM_PRICE, "<") <> 0 THEN SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1) + (SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, "<") + 1) - SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1)) / 2
		WHEN INSTR(ITEM_PRICE, ">") <> 0 THEN SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, ">") + 1) / 2
		ELSE 0
	END)) AS AMOUNT
FROM vendeur_1 
GROUP BY PRODUCT_TYPE, PRODUCT_FAMILY;

SELECT COUNT(*) FROM produit_1;
SELECT * FROM produit_1 LIMIT 100;

DROP TABLE IF EXISTS produit_2;
CREATE TABLE produit_2 AS
SELECT 
	PRODUCT_TYPE, 
	PRODUCT_FAMILY,
	SUM((CASE 
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 AND SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) = "" THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) / 2
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 THEN SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) + (SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) - SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1)) / 2
		WHEN INSTR(PURCHASE_COUNT, ">") <> 0 THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, ">") + 1) / 2
		ELSE 0
	END) * (CASE 
		WHEN INSTR(ITEM_PRICE, "<") <> 0 AND SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1) = "" THEN SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, "<") + 1) / 2
		WHEN INSTR(ITEM_PRICE, "<") <> 0 THEN SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1) + (SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, "<") + 1) - SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1)) / 2
		WHEN INSTR(ITEM_PRICE, ">") <> 0 THEN SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, ">") + 1) / 2
		ELSE 0
	END)) AS AMOUNT
FROM vendeur_2 
GROUP BY PRODUCT_TYPE, PRODUCT_FAMILY;

SELECT COUNT(*) FROM produit_2;
SELECT * FROM produit_2 LIMIT 100;

DROP TABLE IF EXISTS produits;
CREATE TABLE produits AS
SELECT 
	PRODUCT_TYPE, 
	PRODUCT_FAMILY,
	SUM((CASE 
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 AND SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) = "" THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) / 2
		WHEN INSTR(PURCHASE_COUNT, "<") <> 0 THEN SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1) + (SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, "<") + 1) - SUBSTR(PURCHASE_COUNT, 1, INSTR(PURCHASE_COUNT, "<") - 1)) / 2
		WHEN INSTR(PURCHASE_COUNT, ">") <> 0 THEN SUBSTR(PURCHASE_COUNT, INSTR(PURCHASE_COUNT, ">") + 1) / 2
		ELSE 0
	END) * (CASE 
		WHEN INSTR(ITEM_PRICE, "<") <> 0 AND SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1) = "" THEN SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, "<") + 1) / 2
		WHEN INSTR(ITEM_PRICE, "<") <> 0 THEN SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1) + (SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, "<") + 1) - SUBSTR(ITEM_PRICE, 1, INSTR(ITEM_PRICE, "<") - 1)) / 2
		WHEN INSTR(ITEM_PRICE, ">") <> 0 THEN SUBSTR(ITEM_PRICE, INSTR(ITEM_PRICE, ">") + 1) / 2
		ELSE 0
	END)) AS AMOUNT
FROM (SELECT *
	FROM vendeur_1
	UNION ALL
	SELECT *
	FROM vendeur_2) as t
GROUP BY PRODUCT_TYPE, PRODUCT_FAMILY;

SELECT COUNT(*) FROM produits;
SELECT * FROM produits LIMIT 100;

DROP TABLE IF EXISTS client_full;
CREATE TABLE client_full
(
	ID INT,
	SHIPPING_MODE VARCHAR(100),
	SHIPPING_PRICE VARCHAR(100),
	WARRANTIES_FLG VARCHAR(100),
	WARRANTIES_PRICE VARCHAR(100),
	CARD_PAYMENT INT(1),
	COUPON_PAYMENT INT(1),
	RSP_PAYMENT INT(1),
	WALLET_PAYMENT INT(1),
	PRICECLUB_STATUS VARCHAR(100),
	REGISTRATION_DATE VARCHAR(100),
	PURCHASE_COUNT VARCHAR(100),
	BUYER_BIRTHDAY_DATE VARCHAR(100),
	BUYER_DEPARTMENT INT,
	BUYING_DATE VARCHAR(100),
	SELLER_SCORE_COUNT VARCHAR(100),
	SELLER_SCORE_AVERAGE INT,
	SELLER_COUNTRY VARCHAR(100),
	SELLER_DEPARTMENT VARCHAR(100),
	PRODUCT_TYPE VARCHAR(100),
	PRODUCT_FAMILY VARCHAR(100),
	ITEM_PRICE VARCHAR(100),
	COUNTRY_KEY VARCHAR(100),
	CARACT VARCHAR(100)
);

LOAD DATA LOCAL INFILE 'C:/Users/Utilisateur/Desktop/dev/sql/tp_sql_1/Base_eval.csv' 
INTO TABLE data.client_full 
FIELDS TERMINATED BY ';'
IGNORE 1 LINES;

SELECT COUNT(*) FROM client_full;
SELECT * FROM client_full LIMIT 100;

-- Je cherche à connaître les cas que je dois traiter dans mon CASE

SELECT 
	t_princ.ITEM_PRICE AS t_princ_ITEM_PRICE, 
	t_compl.ITEM_PRICE AS t_compl_ITEM_PRICE
FROM
	(SELECT * FROM client_full WHERE UPPER(CARACT) LIKE '%PRINC%') AS t_princ,
	(SELECT * FROM client_full WHERE UPPER(CARACT) LIKE '%COMPL%') AS t_compl
WHERE t_princ.ID = t_compl.ID
GROUP BY t_princ.ITEM_PRICE, t_compl.ITEM_PRICE

-- p(x<y), c(x<y)
-- p(x<y), c(x)
-- p(<x),  c(<x)
-- p(<x),  c(x)

DROP TABLE IF EXISTS vente_finale;
CREATE TABLE vente_finale AS
SELECT 
	t_princ.ID,
	t_princ.SHIPPING_MODE,
	t_princ.SHIPPING_PRICE,
	t_princ.WARRANTIES_FLG,
	t_princ.WARRANTIES_PRICE,
	t_princ.CARD_PAYMENT,
	t_princ.COUPON_PAYMENT,
	t_princ.RSP_PAYMENT,
	t_princ.WALLET_PAYMENT,
	t_princ.PRICECLUB_STATUS,
	t_princ.REGISTRATION_DATE,
	t_princ.PURCHASE_COUNT,
	t_princ.BUYER_BIRTHDAY_DATE,
	t_princ.BUYER_DEPARTMENT,
	t_princ.BUYING_DATE,
	t_princ.SELLER_SCORE_COUNT,
	t_princ.SELLER_SCORE_AVERAGE,
	t_princ.SELLER_COUNTRY,
	t_princ.SELLER_DEPARTMENT,
	t_princ.PRODUCT_TYPE,
	t_princ.PRODUCT_FAMILY,
	CASE
		WHEN -- p(<x),  c(<x)
			INSTR(t_princ.ITEM_PRICE, "<") <> 0 AND 
			SUBSTR(t_princ.ITEM_PRICE, 1, INSTR(t_princ.ITEM_PRICE, "<") - 1) = "" AND
			INSTR(t_compl.ITEM_PRICE, "<") <> 0 AND 
			SUBSTR(t_compl.ITEM_PRICE, 1, INSTR(t_compl.ITEM_PRICE, "<") - 1) = ""			
			THEN 
				CONCAT(
					'<',
					(
						SUBSTR(t_princ.ITEM_PRICE, INSTR(t_princ.ITEM_PRICE, "<") + 1) +
						SUBSTR(t_compl.ITEM_PRICE, INSTR(t_compl.ITEM_PRICE, "<") + 1))
					)
		WHEN -- p(x<y), c(x<y)
			INSTR(t_princ.ITEM_PRICE, "<") <> 0 AND
			INSTR(t_compl.ITEM_PRICE, "<") <> 0 			
			THEN 
				CONCAT(
					(
						SUBSTR(t_princ.ITEM_PRICE, 1, INSTR(t_princ.ITEM_PRICE, "<") - 1) +
						SUBSTR(t_compl.ITEM_PRICE, 1, INSTR(t_compl.ITEM_PRICE, "<") - 1)
				    ), 
					'<', 
					(
						SUBSTR(t_princ.ITEM_PRICE, INSTR(t_princ.ITEM_PRICE, "<") + 1) + 
						SUBSTR(t_compl.ITEM_PRICE, INSTR(t_compl.ITEM_PRICE, "<") + 1)
					)
				)
		WHEN -- p(<x),  c(x)
			INSTR(t_princ.ITEM_PRICE, "<") <> 0 AND 
			SUBSTR(t_princ.ITEM_PRICE, 1, INSTR(t_princ.ITEM_PRICE, "<") - 1) = ""
			THEN
				CONCAT(
					'<',
					(
						SUBSTR(t_princ.ITEM_PRICE, INSTR(t_princ.ITEM_PRICE, "<") + 1) +
						t_compl.ITEM_PRICE
					)
				)
		ELSE -- p(x<y), c(x)
			CONCAT(
				(
					SUBSTR(t_princ.ITEM_PRICE, 1, INSTR(t_princ.ITEM_PRICE, "<") - 1) +
					t_compl.ITEM_PRICE
				), 
				'<', 
				(
					SUBSTR(t_princ.ITEM_PRICE, INSTR(t_princ.ITEM_PRICE, "<") + 1) + 
					t_compl.ITEM_PRICE
				)
			)
	END AS ITEM_PRICE,
	t_princ.COUNTRY_KEY
FROM 
	(SELECT * FROM client_full WHERE UPPER(CARACT) LIKE '%PRINC%') AS t_princ,
	(SELECT * FROM client_full WHERE UPPER(CARACT) LIKE '%COMPL%') AS t_compl
WHERE t_princ.ID = t_compl.ID
	UNION ALL -- J'utilise ca pour ajouter ceux qui n'ont pas été modifiés. On peut faire plus simple mais le when du haut m'a épuisé
SELECT 	
	ID,
	SHIPPING_MODE,
	SHIPPING_PRICE,
	WARRANTIES_FLG,
	WARRANTIES_PRICE,
	CARD_PAYMENT,
	COUPON_PAYMENT,
	RSP_PAYMENT,
	WALLET_PAYMENT,
	PRICECLUB_STATUS,
	REGISTRATION_DATE,
	PURCHASE_COUNT,
	BUYER_BIRTHDAY_DATE,
	BUYER_DEPARTMENT,
	BUYING_DATE,
	SELLER_SCORE_COUNT,
	SELLER_SCORE_AVERAGE,
	SELLER_COUNTRY,
	SELLER_DEPARTMENT,
	PRODUCT_TYPE,
	PRODUCT_FAMILY, 
	ITEM_PRICE,
	COUNTRY_KEY
FROM client_full 
WHERE client_full.ID NOT IN (
	SELECT ID FROM client_full WHERE UPPER(CARACT) LIKE '%COMPL%'
)
ORDER BY ID;

SELECT COUNT(*) FROM vente_finale;
SELECT * FROM vente_finale LIMIT 100;

